#doctrine:
#    dbal:
#        url: '%env(resolve:GRINWAY_SERVICE_DATABASE_URL)%'
#    orm:
#        auto_generate_proxy_classes: '%kernel.debug%'
#        auto_mapping: true
#
# To be able to test MySqlUtil
when@test:
    doctrine:
        dbal:
            url: '%env(resolve:GRINWAY_SERVICE_DATABASE_URL)%'
            server_version: '8.0.40'

            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'
        orm:
            controller_resolver:
                auto_mapping: false
            auto_generate_proxy_classes: '%kernel.debug%'
            auto_mapping: true
