#doctrine:
#    dbal:
#        url: '%env(resolve:GRINWAY_SERVICE_DATABASE_URL)%'
#    orm:
#        auto_generate_proxy_classes: '%kernel.debug%'
#        auto_mapping: true

# To be able to test MySqlUtil
when@test:
    doctrine:
        dbal:
            url: '%env(resolve:GRINWAY_SERVICE_DATABASE_URL)%'
            server_version: '8.0.40'
        orm:
            controller_resolver:
                auto_mapping: false
            auto_generate_proxy_classes: '%kernel.debug%'
            auto_mapping: true
