#doctrine:
#    dbal:
#        url: '%env(resolve:GRINWAY_SERVICE_DATABASE_URL)%'
#    orm:
#        auto_generate_proxy_classes: '%kernel.debug%'
#        auto_mapping: true
#
# To be able to test MySqlUtil
when@test:
    doctrine:
        dbal:
            url: '%env(resolve:GRINWAY_SERVICE_DATABASE_URL)%'
            server_version: '8.0.40'

            dbname_suffix: '_test%env(default::TEST_TOKEN)%'
        orm:
            controller_resolver:
                auto_mapping: false
            auto_generate_proxy_classes: '%kernel.debug%'
            auto_mapping: true
            mappings:
                App:
                    prefix: 'GrinWay\Service\Test\Entity'
                    is_bundle: false
                    type: "attribute"
                    dir: '%kernel.project_dir%/src/Test/Entity'
                    mapping: true
            dql:
                string_functions:
                    leave_only_numbers: 'GrinWay\Service\Doctrine\Function\LeaveOnlyNumbers'
                    dateinterval_to_sec: 'GrinWay\Service\Doctrine\Function\DateIntervalToSec'
