services:

    _defaults:
        autoconfigure: false
        autowire: false

    GrinWay\Service\Service\Currency:
        class: GrinWay\Service\Service\Currency
        arguments:
            $serviceLocator: !service_locator
                grinwayServiceCurrencyFixerLatest: '@grinway_service.currency.fixer_latest'
                currencyCachePool: '@grinway_service.cache_pool.currency'
                serializer: '@serializer'
                validator: '@validator'
                pa: '@Symfony\Component\PropertyAccess\PropertyAccessorInterface'

    grinway_service.currency: '@GrinWay\Service\Service\Currency'
