services:

    _defaults:
        autoconfigure: false
        autowire: false

    .grinway_service.event_listener.doctrine.date_time_to_utc_before_to_database:
        class: 'GrinWay\Service\EventListener\Doctrine\DateTimeToUtcBeforeToDatabaseEventListener'
        arguments:
            $serviceLocator: !service_locator
                property_accessor: '@property_accessor'
        tags:
        -   name: !php/const GrinWay\Service\Contract\Doctrine\DoctrineEventListenerInterface::TAG
        -   name: 'doctrine.event_listener'
            event: !php/const Doctrine\ORM\Events::onFlush

    .grinway_service.event_listener.doctrine.created_at:
        class: 'GrinWay\Service\EventListener\Doctrine\CreatedAtEventListener'
        tags:
        -   name: !php/const GrinWay\Service\Contract\Doctrine\DoctrineEventListenerInterface::TAG
        -   name: 'doctrine.event_listener'
            event: !php/const Doctrine\ORM\Events::prePersist

    .grinway_service.event_listener.doctrine.updated_at:
        class: 'GrinWay\Service\EventListener\Doctrine\UpdatedAtEventListener'
        tags:
        -   name: !php/const GrinWay\Service\Contract\Doctrine\DoctrineEventListenerInterface::TAG
        -   name: 'doctrine.event_listener'
            event: !php/const Doctrine\ORM\Events::preUpdate
