services:

    _defaults:
        autoconfigure: false
        autowire: false

    GrinWay\Service\Validator\:
        resource: '../../../src/Validator/**Validator.php'
        tags:
        -    name: 'validator.constraint_validator'
