name: tests

env:
   APP_CURRENCY_FIXER_API_KEY: "${{ secrets.APP_CURRENCY_FIXER_API_KEY }}"
   APP_DEFAULT_LOCALE: "${{ secrets.APP_DEFAULT_LOCALE }}"
   APP_DATABASE_BACKUP_ABS_PATH: "${{ secrets.APP_DATABASE_BACKUP_ABS_PATH }}"
   APP_DATABASE_NAME: "${{ secrets.APP_DATABASE_NAME }}"
   APP_DATABASE_PORT: "${{ secrets.APP_DATABASE_PORT }}"
   APP_DATABASE_USER: "${{ secrets.APP_DATABASE_USER }}"
   APP_DATABASE_IP: "${{ secrets.APP_DATABASE_IP }}"
   APP_DATABASE_PORT_WITH_DOTS: "${{ secrets.APP_DATABASE_PORT_WITH_DOTS }}"
   APP_TEST_DATABASE_PASSWORD: "${{ secrets.APP_TEST_DATABASE_PASSWORD }}"
   GRINWAY_SERVICE_DATABASE_URL: "mysql://${{ secrets.APP_DATABASE_USER }}:${{ secrets.APP_TEST_DATABASE_PASSWORD }}@${{ secrets.APP_DATABASE_IP }}${{ secrets.APP_DATABASE_PORT_WITH_DOTS }}/${{ secrets.APP_DATABASE_NAME }}?sslmode=disable&charset=utf8mb4"

on:
  workflow_dispatch: ~
  #push:
  #  branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:

  tests:

    runs-on: ubuntu-latest
    
    steps:
    
    - name: PHP Installation
      uses: 'shivammathur/setup-php@2cb9b829437ee246e9b3cac53555a39208ca6d28'
      with:
        php-version: '8.4'

    - name: Donwload the project
      uses: actions/checkout@v4
    
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install Composer Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - uses: mirromutth/mysql-action@v1.1
      with:
        host port: "${{ secrets.APP_DATABASE_PORT }}" # Optional, default value is 3306. The port of host
        container port: "${{ secrets.APP_DATABASE_PORT }}" # Optional, default value is 3306. The port of container
        character set server: 'utf8' # Optional, default value is 'utf8mb4'. The '--character-set-server' option for mysqld
        collation server: 'utf8_general_ci' # Optional, default value is 'utf8mb4_general_ci'. The '--collation-server' option for mysqld
        mysql version: '8.0' # Optional, default value is "latest". The version of the MySQL
        mysql database: "${{ secrets.APP_DATABASE_NAME }}" # Optional, default value is "test". The specified database which will be create
        mysql root password: "${{ secrets.APP_TEST_DATABASE_PASSWORD }}" # Required if "mysql user" is empty, default is empty. The root superuser password
        mysql user: "${{ secrets.APP_DATABASE_USER }}" # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
        mysql password: "${{ secrets.APP_TEST_DATABASE_PASSWORD }}" # Required if "mysql user" exists. The password for the "mysql user"
    
    #- name: Create The Database
    #  run: |
    #    php bin/console doctrine:database:create --if-not-exists --env test
    
    - name: tests
      run: vendor/bin/phpunit
